#!/usr/bin/env bash
set -euo pipefail

# requirements.lock is the only input to the production Lambda bundle: both
# .github/workflows/deploy.yml and build.sh install it with --no-deps, so
# anything the lock omits is simply absent from the deployed zip.
#
# That makes *where* the lock is resolved a correctness property, not a
# convenience. Resolving on the host is wrong: environment markers are
# evaluated against the host, so a macOS arm64 laptop reports
# platform_machine == "arm64" and drops SQLAlchemy's greenlet dependency,
# which the aarch64 Lambda actually requires, while an x86_64 CI runner keeps
# it. Same source, two different bundles.
#
# uv resolves against an explicit target triple instead of the running
# machine, so the output below is a pure function of requirements.txt. The
# resolver flags mirror the install flags in deploy.yml and build.sh
# one-for-one -- python version, platform tag and wheels-only. Changing one
# without the other reopens exactly the gap this script exists to close.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE_FILE="${ROOT_DIR}/requirements.txt"
OUTPUT_FILE="${1:-${ROOT_DIR}/requirements.lock}"
UV_BIN="${UV_COMMAND:-uv}"
PYTHON_BIN="${PYTHON_BIN:-python3}"

UV_REQUIRED_VERSION="0.12.7"

# Keep in sync with the pip install flags in deploy.yml and build.sh.
TARGET_PYTHON_VERSION="3.12"
TARGET_PLATFORM="aarch64-manylinux2014"

if ! command -v "${UV_BIN}" >/dev/null 2>&1; then
  echo "error: uv ${UV_REQUIRED_VERSION} is required; install it with 'pip install uv==${UV_REQUIRED_VERSION}'" >&2
  exit 1
fi

ACTUAL_UV_VERSION="$("${UV_BIN}" --version | awk '{print $2}')"
if [[ "${ACTUAL_UV_VERSION}" != "${UV_REQUIRED_VERSION}" ]]; then
  echo "error: requirements.lock must be compiled with uv ${UV_REQUIRED_VERSION}, found ${ACTUAL_UV_VERSION}" >&2
  exit 1
fi

TEMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/requirements-compile.XXXXXX")"
trap 'rm -rf "${TEMP_DIR}"' EXIT
COMPILED_BODY="${TEMP_DIR}/requirements.body"
FINAL_LOCK="${TEMP_DIR}/requirements.lock"

# uv treats an existing output file as a set of preferences, so routine
# regeneration keeps the current pins instead of silently drifting onto every
# upstream release. Seed it so a plain re-run is a no-op.
if [[ -f "${OUTPUT_FILE}" ]]; then
  cp "${OUTPUT_FILE}" "${COMPILED_BODY}"
else
  : > "${COMPILED_BODY}"
fi

(
  cd "${ROOT_DIR}"
  "${UV_BIN}" pip compile \
    --quiet \
    --python-version "${TARGET_PYTHON_VERSION}" \
    --python-platform "${TARGET_PLATFORM}" \
    --only-binary :all: \
    --no-header \
    --no-emit-index-url \
    --strip-extras \
    --output-file "${COMPILED_BODY}" \
    requirements.txt
)

SOURCE_SHA="$("${PYTHON_BIN}" -c 'import hashlib, pathlib, sys; print(hashlib.sha256(pathlib.Path(sys.argv[1]).read_bytes()).hexdigest())' "${SOURCE_FILE}")"
{
  printf '%s\n' \
    '#' \
    "# This file is autogenerated by uv ${UV_REQUIRED_VERSION}." \
    "# Resolution target: CPython ${TARGET_PYTHON_VERSION} / ${TARGET_PLATFORM} / wheels only." \
    '# The target is pinned, so this file does not depend on the machine that' \
    '# generated it: a macOS arm64 laptop and the x86_64 CI runner produce' \
    '# byte-identical output.' \
    "# requirements.txt sha256: ${SOURCE_SHA}" \
    '# To update:' \
    '#' \
    '#    ./scripts/compile_requirements.sh' \
    '#'
  cat "${COMPILED_BODY}"
} > "${FINAL_LOCK}"

mkdir -p "$(dirname "${OUTPUT_FILE}")"
mv "${FINAL_LOCK}" "${OUTPUT_FILE}"
