#!/usr/bin/env bash
set -euo pipefail

# requirements.lock is the only input to the production Lambda bundle: both
# .github/workflows/deploy.yml and build.sh install it with --no-deps, so
# anything the lock omits is simply absent from the deployed zip.
#
# That makes *where* and *when* the lock is resolved a correctness property,
# not a convenience:
#
#   * Where. Environment markers are evaluated against the resolving machine,
#     so a macOS arm64 laptop reports platform_machine == "arm64" and drops
#     SQLAlchemy's greenlet dependency, which the aarch64 Lambda actually
#     requires, while an x86_64 CI runner keeps it. uv resolves against an
#     explicit target triple instead, so the host does not matter.
#   * When. A resolver that is free to pick "whatever is newest right now"
#     produces a different lock every day, which would make the drift check
#     unrunnable. EXCLUDE_NEWER freezes the index at a fixed instant.
#
# Together those two make the output a pure function of requirements.txt and
# the constants below. Nothing is seeded from the previous lock, so a
# hand-edited pin does not survive a recompile -- which is what lets
# check_requirements_lock.sh detect a tampered lock and not merely a tampered
# requirements.txt.
#
# The resolver flags mirror the install flags in deploy.yml and build.sh
# one-for-one. Changing one without the other reopens the gap this script
# exists to close.
#
# To upgrade dependencies -- the only supported way -- move EXCLUDE_NEWER
# forward and re-run. That lands as a one-line, reviewable diff next to the
# pin changes it causes.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE_FILE="${ROOT_DIR}/requirements.txt"
OUTPUT_FILE="${1:-${ROOT_DIR}/requirements.lock}"
UV_BIN="${UV_COMMAND:-uv}"
PYTHON_BIN="${PYTHON_BIN:-python3}"

UV_REQUIRED_VERSION="0.12.7"

# Keep in sync with the pip install flags in deploy.yml and build.sh.
TARGET_PYTHON_VERSION="3.12"
TARGET_PLATFORM="aarch64-manylinux2014"

# Index freeze. Bump this (and only this) to take newer releases.
EXCLUDE_NEWER="2026-08-29T00:00:00Z"

if ! command -v "${UV_BIN}" >/dev/null 2>&1; then
  echo "error: uv ${UV_REQUIRED_VERSION} is required; install it with 'pip install uv==${UV_REQUIRED_VERSION}'" >&2
  exit 1
fi

ACTUAL_UV_VERSION="$("${UV_BIN}" --version | awk '{print $2}')"
if [[ "${ACTUAL_UV_VERSION}" != "${UV_REQUIRED_VERSION}" ]]; then
  echo "error: requirements.lock must be compiled with uv ${UV_REQUIRED_VERSION}, found ${ACTUAL_UV_VERSION}" >&2
  exit 1
fi

TEMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/requirements-compile.XXXXXX")"
trap 'rm -rf "${TEMP_DIR}"' EXIT
COMPILED_BODY="${TEMP_DIR}/requirements.body"
FINAL_LOCK="${TEMP_DIR}/requirements.lock"

(
  cd "${ROOT_DIR}"
  "${UV_BIN}" pip compile \
    --quiet \
    --python-version "${TARGET_PYTHON_VERSION}" \
    --python-platform "${TARGET_PLATFORM}" \
    --only-binary :all: \
    --exclude-newer "${EXCLUDE_NEWER}" \
    --no-header \
    --no-emit-index-url \
    --strip-extras \
    --output-file "${COMPILED_BODY}" \
    requirements.txt
)

SOURCE_SHA="$("${PYTHON_BIN}" -c 'import hashlib, pathlib, sys; print(hashlib.sha256(pathlib.Path(sys.argv[1]).read_bytes()).hexdigest())' "${SOURCE_FILE}")"
{
  printf '%s\n' \
    '#' \
    "# This file is autogenerated by uv ${UV_REQUIRED_VERSION}. Do not edit it by hand:" \
    '# scripts/check_requirements_lock.sh recompiles from scratch and will reject' \
    '# any pin that a fresh resolution does not produce.' \
    "# Resolution target: CPython ${TARGET_PYTHON_VERSION} / ${TARGET_PLATFORM} / wheels only." \
    "# Index frozen at:   ${EXCLUDE_NEWER}" \
    '# The target and the freeze are both pinned, so this file does not depend on' \
    '# the machine or the day that produced it: a macOS arm64 laptop and the' \
    '# x86_64 CI runner produce byte-identical output.' \
    "# requirements.txt sha256: ${SOURCE_SHA}" \
    '# To regenerate (or to take newer releases, after moving EXCLUDE_NEWER):' \
    '#' \
    '#    ./scripts/compile_requirements.sh' \
    '#'
  cat "${COMPILED_BODY}"
} > "${FINAL_LOCK}"

mkdir -p "$(dirname "${OUTPUT_FILE}")"
mv "${FINAL_LOCK}" "${OUTPUT_FILE}"
