#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE_FILE="${ROOT_DIR}/requirements.txt"
OUTPUT_FILE="${1:-${ROOT_DIR}/requirements.lock}"
PIP_COMPILE_BIN="${PIP_COMPILE_COMMAND:-pip-compile}"
PYTHON_BIN="${PYTHON_BIN:-python}"

if [[ "$("${PYTHON_BIN}" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')" != "3.12" ]]; then
  echo "error: requirements.lock must be compiled with Python 3.12" >&2
  exit 1
fi

if [[ "$("${PIP_COMPILE_BIN}" --version)" != "pip-compile, version 7.6.1" ]]; then
  echo "error: requirements.lock must be compiled with pip-tools 7.6.1" >&2
  exit 1
fi

TEMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/requirements-compile.XXXXXX")"
trap 'rm -rf "${TEMP_DIR}"' EXIT
COMPILED_BODY="${TEMP_DIR}/requirements.body"
FINAL_LOCK="${TEMP_DIR}/requirements.lock"

# pip-compile reuses compatible pins from its output file unless --upgrade is
# requested. Seed that file so routine regeneration preserves the current lock.
if [[ -f "${OUTPUT_FILE}" ]]; then
  cp "${OUTPUT_FILE}" "${COMPILED_BODY}"
else
  : > "${COMPILED_BODY}"
fi

(
  cd "${ROOT_DIR}"
  "${PIP_COMPILE_BIN}" \
    --quiet \
    --no-header \
    --no-emit-index-url \
    --strip-extras \
    --output-file "${COMPILED_BODY}" \
    requirements.txt
)

SOURCE_SHA="$("${PYTHON_BIN}" -c 'import hashlib, pathlib, sys; print(hashlib.sha256(pathlib.Path(sys.argv[1]).read_bytes()).hexdigest())' "${SOURCE_FILE}")"
{
  printf '%s\n' \
    '#' \
    '# This file is autogenerated by pip-compile with Python 3.12 and pip-tools 7.6.1.' \
    '# Resolution baseline: CPython 3.12 / manylinux2014_aarch64 Lambda.' \
    "# requirements.txt sha256: ${SOURCE_SHA}" \
    '# To update:' \
    '#' \
    '#    ./scripts/compile_requirements.sh' \
    '#'
  cat "${COMPILED_BODY}"
} > "${FINAL_LOCK}"

mkdir -p "$(dirname "${OUTPUT_FILE}")"
mv "${FINAL_LOCK}" "${OUTPUT_FILE}"
